services:
  mysql_db:
    image: mysql:latest
    container_name: mini-erp-mysql
    restart: always
    env_file:
      - .env
    volumes:
      - mini-erp-dp-volume:/var/lib/mysql
  api:
    build:
      context: .
      dockerfile: DockerFile
    container_name: mini-erp-api
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mysql_db
  
volumes:
  mini-erp-dp-volume:
  