services:
  mysql_db:
    image: mysql:latest
    container_name: mini-erp-mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3012:3306"
    volumes:
      - mini-erp-db-volume:/var/lib/mysql
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mini-erp-api
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mysql_db
  
volumes:
  mini-erp-db-volume: